[[tool]]
name = "interm"
script = "bin/interm"
is_executable = true

[[tool]]
name = "scan-ports"
script = "tools/scan-ports/scan-ports.py"

[[tool]]
name = "find-projects"
script = "tools/find-projects/find-projects.py"

[[tool]]
name = "sort-files"
script = "tools/sort-files/sort-files.py"

[[tool]]
name = "test-endpoints"
script = "tools/test-endpoints/test-endpoints.py"
