[[tool]]
name = "scan-ports"
script = "tools/scan-ports/scan-ports.py"

[[tool]]
name = "find-projects"
script = "tools/find-projects/find-projects.py"

[[tool]]
name = "interm"
script = "bin/interm"
is_executable = true