# Default configuration for template-tool

# General options
verbose = false
timeout = 30

# Example settings
[settings]
example_option = "default value"
max_items = 100

# Example categories
[categories]
category1 = "Description for category 1"
category2 = "Description for category 2"

# Example feature flags
[features]
enable_feature1 = true
enable_feature2 = false
