# Global configuration for IntermCLI (TOML format)
# This file sets defaults for all tools and can be overridden by tool-specific configs.


[common]
log_level = "INFO"                # Logging verbosity for all tools
default_editor = "code"           # Editor for opening files/projects
timeout = 30                      # Default network timeout (seconds)
dry_run = false                   # Default dry-run mode for safe operations
output_dir = "~/intermcli/output" # Default output directory for reports/logs

[paths]
projects = ["~/development", "~/projects", "~/code", "~/workspace", "~/src"]
downloads = "~/Downloads"
documents = "~/Documents"

[platform]
linux_specific_dir = "/opt/projects"
macos_specific_dir = "/Applications/Projects"

[features]
enable_rich_output = true         # Enable rich/colorized output if available
enable_enhanced_mode = true       # Enable enhanced features if optional deps are present

[network]
default_ports = [80, 443, 22, 8080]
scan_threads = 10                 # Default number of threads for scanning

[api]
default_headers = { "User-Agent" = "IntermCLI/1.0" }
