name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Test core functionality (no optional deps)
      run: |
        python tools/scan-ports/scan-ports.py --help
        python tools/find-projects/find-projects.py --help
        
    - name: Install optional dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test enhanced functionality
      run: |
        python tools/scan-ports/scan-ports.py localhost --enhanced
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v